name: Verify Human Identity
on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: 'lakr'
        required: true
        default: 'lakr'
      agent_description:
        description: 'lakr'
        required: true
        default: 'lakr AI Agent'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install script dependencies
        run: |
          cd scripts
          npm install

      - name: Step 1 - Create new Ethereum Identity
        run: node scripts/createNewEthereumIdentity.js

      - name: Step 2 - Link Human to Agent
        run: |
          node scripts/manualLinkHumanToAgent.js --challenge '{"name": "lakr", "description": "lakr AI Agent"}'
